### ISSUE TITLE
Cassandra PHP client - Invalid or unsupported protocol version

### ISSUE THREAD

**Issue by kevas** [evseevnn-zz/php-cassandra-binary#76]
I am trying your php client.

My code:

```
$nodes = ['127.0.0.1:9042'];
$database = new \evseevnn\Cassandra\Database($nodes, 'people');
$database->connect();
```

I get this exception error:
`evseevnn\Cassandra\Exception\ConnectionException: Protocol error: Invalid or unsupported protocol version (1); the lowest supported version is 3 and the greatest is 4`

Where do I set protocol version?
Thank you.

R.

**Comment by evseevnn** [comment]
Sorry, this repository deprecated and not maintained anymore.
Please use [https://github.com/duoshuo/php-cassandra](url)
